export const NATIONALITIES = [
  { iconCode: "AU", name: "Australian", color: "magenta" },
  { iconCode: "BR", name: "Brazilian", color: "red" },
  { iconCode: "CA", name: "Canadian", color: "volcano" },
  { iconCode: "CH", name: "Swiss", color: "orange" },
  { iconCode: "DE", name: "German", color: "gold" },
  { iconCode: "DK", name: "Danish", color: "lime" },
  { iconCode: "ES", name: "Spanish", color: "green" },
  { iconCode: "FI", name: "Finnish", color: "cyan" },
  { iconCode: "FR", name: "French", color: "blue" },
  { iconCode: "GB", name: "British", color: "#109d73" },
  { iconCode: "IE", name: "Irish", color: "purple" },
  { iconCode: "IR", name: "Iranian", color: "#f50" },
  { iconCode: "NO", name: "Norwegian", color: "#2db7f5" },
  { iconCode: "NL", name: "Dutch", color: "#87d068" },
  { iconCode: "NZ", name: "New Zealander", color: "#9e1068" },
  { iconCode: "TR", name: "Turkish", color: "#ffd666" },
  { iconCode: "US", name: "American" },
];
